version: "3.9"
services:
  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  neo4j:
    build:
      context: ./neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/strongpassword"

  data-seed:
    build:
      context: ./seed
    container_name: data-seed
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/
    command: ["python", "insert_mock_data.py"]

  migration:
    build:
      context: ./migration
    container_name: migration
    depends_on:
      - data-seed
      - neo4j
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/
      - NEO4J_URI=bolt://neo4j:7687/
      - NEO4J_AUTH=neo4j/strongpassword
    command: ["python", "mongo_to_neo4j.py"]

volumes:
  mongodb_data:
  neo4j_data:
