version: "3.9"
services:
  mongodb:
    build:
      context: ./mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  python-app:
    build:
      context: ./python-app
    container_name: python-app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/

  neo4j:
    build:
      context: ./neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/strongpassword"
volumes:
  mongodb_data:
  neo4j_data:
